/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as MaintenancePreviewRouteImport } from './routes/maintenance-preview'
import { Route as HsesRouteImport } from './routes/hses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminManageRentalsRouteImport } from './routes/admin/manage-rentals'
import { Route as AdminInvoicesRouteImport } from './routes/admin/invoices'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AppSiteContentRouteImport } from './routes/_app/site-content'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppManageRentalsRouteImport } from './routes/_app/manage-rentals'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppBookingsRouteImport } from './routes/_app/bookings'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices.index'
import { Route as AdminInvoicesNewRouteImport } from './routes/admin/invoices/new'
import { Route as AdminInvoicesIdRouteImport } from './routes/admin/invoices/$id'
import { Route as AdminCustomersNewRouteImport } from './routes/admin/customers/new'
import { Route as AppInvoicesNewRouteImport } from './routes/_app/invoices.new'
import { Route as AppInvoicesIdRouteImport } from './routes/_app/invoices.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenancePreviewRoute = MaintenancePreviewRouteImport.update({
  id: '/maintenance-preview',
  path: '/maintenance-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const HsesRoute = HsesRouteImport.update({
  id: '/hses',
  path: '/hses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageRentalsRoute = AdminManageRentalsRouteImport.update({
  id: '/manage-rentals',
  path: '/manage-rentals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AppSiteContentRoute = AppSiteContentRouteImport.update({
  id: '/site-content',
  path: '/site-content',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppManageRentalsRoute = AppManageRentalsRouteImport.update({
  id: '/manage-rentals',
  path: '/manage-rentals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AdminInvoicesNewRoute = AdminInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminInvoicesRoute,
} as any)
const AdminInvoicesIdRoute = AdminInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminInvoicesRoute,
} as any)
const AdminCustomersNewRoute = AdminCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/hses': typeof HsesRoute
  '/maintenance-preview': typeof MaintenancePreviewRoute
  '/portal': typeof PortalRoute
  '/projects': typeof ProjectsRoute
  '/rentals': typeof RentalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/bookings': typeof AppBookingsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/manage-rentals': typeof AppManageRentalsRoute
  '/settings': typeof AppSettingsRoute
  '/site-content': typeof AppSiteContentRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/manage-rentals': typeof AdminManageRentalsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/invoices/': typeof AppInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/hses': typeof HsesRoute
  '/maintenance-preview': typeof MaintenancePreviewRoute
  '/portal': typeof PortalRoute
  '/projects': typeof ProjectsRoute
  '/rentals': typeof RentalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/bookings': typeof AppBookingsRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/manage-rentals': typeof AppManageRentalsRoute
  '/settings': typeof AppSettingsRoute
  '/site-content': typeof AppSiteContentRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/manage-rentals': typeof AdminManageRentalsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/invoices': typeof AppInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/hses': typeof HsesRoute
  '/maintenance-preview': typeof MaintenancePreviewRoute
  '/portal': typeof PortalRoute
  '/projects': typeof ProjectsRoute
  '/rentals': typeof RentalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/_app/bookings': typeof AppBookingsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/manage-rentals': typeof AppManageRentalsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/site-content': typeof AppSiteContentRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/manage-rentals': typeof AdminManageRentalsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/clients'
    | '/contact'
    | '/hses'
    | '/maintenance-preview'
    | '/portal'
    | '/projects'
    | '/rentals'
    | '/reset-password'
    | '/services'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/manage-rentals'
    | '/settings'
    | '/site-content'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/invoices'
    | '/admin/manage-rentals'
    | '/admin/settings'
    | '/admin/'
    | '/invoices/$id'
    | '/invoices/new'
    | '/admin/customers/new'
    | '/admin/invoices/$id'
    | '/admin/invoices/new'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/clients'
    | '/contact'
    | '/hses'
    | '/maintenance-preview'
    | '/portal'
    | '/projects'
    | '/rentals'
    | '/reset-password'
    | '/services'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/manage-rentals'
    | '/settings'
    | '/site-content'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/invoices'
    | '/admin/manage-rentals'
    | '/admin/settings'
    | '/admin'
    | '/invoices/$id'
    | '/invoices/new'
    | '/admin/customers/new'
    | '/admin/invoices/$id'
    | '/admin/invoices/new'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/admin'
    | '/auth'
    | '/clients'
    | '/contact'
    | '/hses'
    | '/maintenance-preview'
    | '/portal'
    | '/projects'
    | '/rentals'
    | '/reset-password'
    | '/services'
    | '/_app/bookings'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/manage-rentals'
    | '/_app/settings'
    | '/_app/site-content'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/invoices'
    | '/admin/manage-rentals'
    | '/admin/settings'
    | '/admin/'
    | '/_app/invoices/$id'
    | '/_app/invoices/new'
    | '/admin/customers/new'
    | '/admin/invoices/$id'
    | '/admin/invoices/new'
    | '/_app/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  HsesRoute: typeof HsesRoute
  MaintenancePreviewRoute: typeof MaintenancePreviewRoute
  PortalRoute: typeof PortalRoute
  ProjectsRoute: typeof ProjectsRoute
  RentalsRoute: typeof RentalsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance-preview': {
      id: '/maintenance-preview'
      path: '/maintenance-preview'
      fullPath: '/maintenance-preview'
      preLoaderRoute: typeof MaintenancePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hses': {
      id: '/hses'
      path: '/hses'
      fullPath: '/hses'
      preLoaderRoute: typeof HsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage-rentals': {
      id: '/admin/manage-rentals'
      path: '/manage-rentals'
      fullPath: '/admin/manage-rentals'
      preLoaderRoute: typeof AdminManageRentalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/site-content': {
      id: '/_app/site-content'
      path: '/site-content'
      fullPath: '/site-content'
      preLoaderRoute: typeof AppSiteContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage-rentals': {
      id: '/_app/manage-rentals'
      path: '/manage-rentals'
      fullPath: '/manage-rentals'
      preLoaderRoute: typeof AppManageRentalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/invoices/new': {
      id: '/admin/invoices/new'
      path: '/new'
      fullPath: '/admin/invoices/new'
      preLoaderRoute: typeof AdminInvoicesNewRouteImport
      parentRoute: typeof AdminInvoicesRoute
    }
    '/admin/invoices/$id': {
      id: '/admin/invoices/$id'
      path: '/$id'
      fullPath: '/admin/invoices/$id'
      preLoaderRoute: typeof AdminInvoicesIdRouteImport
      parentRoute: typeof AdminInvoicesRoute
    }
    '/admin/customers/new': {
      id: '/admin/customers/new'
      path: '/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AdminCustomersNewRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBookingsRoute: typeof AppBookingsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppManageRentalsRoute: typeof AppManageRentalsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSiteContentRoute: typeof AppSiteContentRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookingsRoute: AppBookingsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppManageRentalsRoute: AppManageRentalsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSiteContentRoute: AppSiteContentRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminCustomersRouteChildren {
  AdminCustomersNewRoute: typeof AdminCustomersNewRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersNewRoute: AdminCustomersNewRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminInvoicesRouteChildren {
  AdminInvoicesIdRoute: typeof AdminInvoicesIdRoute
  AdminInvoicesNewRoute: typeof AdminInvoicesNewRoute
}

const AdminInvoicesRouteChildren: AdminInvoicesRouteChildren = {
  AdminInvoicesIdRoute: AdminInvoicesIdRoute,
  AdminInvoicesNewRoute: AdminInvoicesNewRoute,
}

const AdminInvoicesRouteWithChildren = AdminInvoicesRoute._addFileChildren(
  AdminInvoicesRouteChildren,
)

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInvoicesRoute: typeof AdminInvoicesRouteWithChildren
  AdminManageRentalsRoute: typeof AdminManageRentalsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInvoicesRoute: AdminInvoicesRouteWithChildren,
  AdminManageRentalsRoute: AdminManageRentalsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  HsesRoute: HsesRoute,
  MaintenancePreviewRoute: MaintenancePreviewRoute,
  PortalRoute: PortalRoute,
  ProjectsRoute: ProjectsRoute,
  RentalsRoute: RentalsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
